kind: pipeline
name: default

steps:
- name: prepare
  image: v7lin/flutter:1.5.4-hotfix.2-stable
  volumes:
  - name: pub-cache
    path: /opt/flutter/.pub-cache
  commands:
  - flutter packages get

#- name: build_runner
#  image: v7lin/flutter:1.5.4-hotfix.2-stable
#  volumes:
#  - name: pub-cache
#    path: /opt/flutter/.pub-cache
#  commands:
#  - flutter packages pub run build_runner build

- name: format
  image: v7lin/flutter:1.5.4-hotfix.2-stable
  volumes:
  - name: pub-cache
    path: /opt/flutter/.pub-cache
  commands:
  - flutter format --dry-run --set-exit-if-changed .

- name: analyze
  image: v7lin/flutter:1.5.4-hotfix.2-stable
  volumes:
  - name: pub-cache
    path: /opt/flutter/.pub-cache
  commands:
  - flutter analyze

- name: test
  image: v7lin/flutter:1.5.4-hotfix.2-stable
  volumes:
  - name: pub-cache
    path: /opt/flutter/.pub-cache
  commands:
  - flutter test --coverage
  - cd example/
  - flutter test

- name: proguard
  image: v7lin/flutter:1.5.4-hotfix.2-stable
  volumes:
  - name: pub-cache
    path: /opt/flutter/.pub-cache
  - name: gradle
    path: /root/.gradle
  commands:
  - cd example/
  - flutter build apk

#- name: coverage
#  image: plugins/codecov:2.0.3
#  settings:
#    token:
#      from_secret: CODECOV_TOKEN
#    files:
#    - ./coverage/lcov.info

volumes:
- name: pub-cache
  temp: {}
- name: gradle
  temp: {}

---
kind: pipeline
name: publish

steps:
- name: publish-check
  image: v7lin/flutter:1.5.4-hotfix.2-stable
  volumes:
  - name: pub-cache
    path: /opt/flutter/.pub-cache
  commands:
  - flutter packages pub publish --dry-run

- name: restore-cache
  image: alpine:3.9.3
  volumes:
  - name: pub-cache
    path: /opt/flutter/.pub-cache
  commands:
  - wget -P /opt/flutter/.pub-cache https://raw.githubusercontent.com/v7lin/pub_credentials/master/credentials.json.enc
  - ls /opt/flutter/.pub-cache

- name: restore-cache-openssl
  image: v7lin/openssl:1.1.1b
  volumes:
  - name: pub-cache
    path: /opt/flutter/.pub-cache
  environment:
    ENC_METHOD:
      from_secret: ENC_METHOD
    ENC_PASSWORD:
      from_secret: ENC_PASSWORD
  commands:
  - openssl enc -d -$ENC_METHOD -k $ENC_PASSWORD -in /opt/flutter/.pub-cache/credentials.json.enc -out /opt/flutter/.pub-cache/credentials.json
  - rm /opt/flutter/.pub-cache/credentials.json.enc
  - ls /opt/flutter/.pub-cache

- name: publish
  image: v7lin/flutter:1.5.4-hotfix.2-stable
  volumes:
  - name: pub-cache
    path: /opt/flutter/.pub-cache
  commands:
  - sudo flutter packages pub publish

- name: save-cache-openssl
  image: v7lin/openssl:1.1.1b
  volumes:
  - name: pub-cache
    path: /opt/flutter/.pub-cache
  environment:
    ENC_METHOD:
      from_secret: ENC_METHOD
    ENC_PASSWORD:
      from_secret: ENC_PASSWORD
  commands:
  - openssl enc -e -$ENC_METHOD -k $ENC_PASSWORD -in /opt/flutter/.pub-cache/credentials.json -out /opt/flutter/.pub-cache/credentials.json.enc
  - rm /opt/flutter/.pub-cache/credentials.json
  - ls /opt/flutter/.pub-cache

- name: save-cache
  image: docker:git
  volumes:
  - name: pub-cache
    path: /opt/flutter/.pub-cache
  commands:
  - git clone https://github.com/v7lin/pub_credentials.git /opt/flutter/.pub-cache/pub_credentials
  - ls /opt/flutter/.pub-cache/pub_credentials
  - mv /opt/flutter/.pub-cache/credentials.json.enc /opt/flutter/.pub-cache/pub_credentials/credentials.json.enc
  - git commit -am "update credentials by ci/cd tools"
  - git push

volumes:
- name: pub-cache
  temp: {}

trigger:
  status:
  - success
  event:
  - tag

depends_on:
- default
